#!/bin/bash
if [ $# -lt 1 ] 
then
	echo "too few"
	exit 1
elif [ $# -gt 1 ]
then	
	echo "too many"
	exit 2
elif [ ! -d $1 ]
then
	echo "incorrect argument type"
	exit 3
else
	fileList=( $1/* )
	counter=1
	for val in $fileList
	do
		if [ -f $val ]
		then
			echo "$counter $val"
			counter=$(( $counter + 1 ))
		fi
	done
fi

size=${#fileList[@]}
last=$(( $size - 1 ))
cmd=( `ls -l ${fileList[$last]}` )

name=${fileList[$last]}
size=${fileList[4]}|cut -d " " -f4
echo "$name $size"
exit 0
