#!/bin/bash

echo "Enter first number: "
read first

echo "Enter second number: "
read second

if [[ $first -lt $second ]]
then
	echo "The bigger number is $second and was typed second"
else
	echo "The bigger number is $first and was typed first"
fi
